In [1]:
import pandas as pd

accomodations_clusters = pd.read_csv('https://raw.githubusercontent.com/gr-oll/SLO_LA_Olympics/main/clusters_central_location.csv')
venues = pd.read_csv('https://raw.githubusercontent.com/gr-oll/SLO_LA_Olympics/main/venues.csv')
time_matrix = pd.read_csv('https://raw.githubusercontent.com/gr-oll/SLO_LA_Olympics/main/time_matrix.csv')
bus_matrix = pd.read_csv('https://raw.githubusercontent.com/gr-oll/SLO_LA_Olympics/main/accomodations_to_venues.csv')
bus_terminals = pd.read_csv('https://raw.githubusercontent.com/gr-oll/SLO_LA_Olympics/main/bus_terminals.csv')

In [2]:
venues = venues.dropna()

In [3]:
import folium

# Create a map centered at the average latitude and longitude
map_center = [accomodations_clusters['avg_latitude'].mean(), accomodations_clusters['avg_longitude'].mean()]
m = folium.Map(location=map_center, zoom_start=10)

# Add markers for each cluster
for _, row in accomodations_clusters.iterrows():
    folium.Marker(
        location=[row['avg_latitude'], row['avg_longitude']],
        popup=f"ID: {row['id']}<br>Total Accommodates: {row['total_accommodates']}<br>Count: {row['count']}",
    ).add_to(m)


# Add markers for each venue
for _, row in venues.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=f"ID: {row['id']}<br>Approx. Capacity: {row['Approx. Capacity']}<br>Venue: {row['Venue']}",
        icon=folium.Icon(color='purple')
    ).add_to(m)
    
# Add markers for each bus terminal
for _, row in bus_terminals.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=f"ID: {row['id']}<br>Terminal: {row['FACILITY']}",
        icon=folium.Icon(color='green')
    ).add_to(m)
# Display the map
m

In [4]:
time_matrix

Unnamed: 0      V1   V2      V3      V4      V5      V6      V7      V8  \
0          V1     0.0  NaN  2540.0   497.0  1185.0  1961.0  2113.0   497.0   
1          V2     NaN  0.0     NaN     NaN     NaN     NaN     NaN     NaN   
2          V3  2748.0  NaN     0.0  2572.0  2685.0  2454.0  1706.0  2572.0   
3          V4   491.0  NaN  2421.0     0.0  1321.0  2097.0  2249.0     0.0   
4          V5  1407.0  NaN  2851.0  1454.0     0.0  2310.0  2462.0  1454.0   
..        ...     ...  ...     ...     ...     ...     ...     ...     ...   
80        A47  1040.0  NaN  2722.0   836.0  1870.0  2582.0  2790.0   836.0   
81        A48  1032.0  NaN  2902.0   806.0  1943.0  2719.0  2871.0   806.0   
82        A49   667.0  NaN  2597.0   373.0  1497.0  2273.0  2426.0   373.0   
83        A50   948.0  NaN  2629.0   744.0  1778.0  2490.0  2698.0   744.0   
84        A51   668.0  NaN  2494.0   222.0  1497.0  2273.0  2426.0   222.0   

        V9  ...     A42     A43     A44     A45     A46     A47     A48  \
0   1840.0  ...  4051.0   814.0  1683.0  2703.0   714.0  1086.0  1064.0   
1      NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2   1999.0  ...  5643.0  2077.0  3248.0  4462.0  2390.0  2816.0  2940.0   
3   1976.0  ...  3747.0   735.0  1379.0  2469.0   439.0   783.0   789.0   
4   2192.0  ...  4182.0  1772.0  2320.0  2700.0  1672.0  2044.0  2052.0   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
80  2465.0  ...  3537.0  1007.0  1228.0  2259.0   687.0     0.0   722.0   
81  2598.0  ...  3637.0  1187.0  1328.0  2359.0   883.0   705.0     0.0   
82  2153.0  ...  3816.0   874.0  1507.0  2538.0   592.0   719.0   458.0   
83  2373.0  ...  3644.0   915.0  1255.0  2367.0   595.0   560.0   916.0   
84  2153.0  ...  3881.0   771.0  1513.0  2603.0   532.0   917.0   871.0   

       A49     A50     A51  
0    714.0  1003.0   563.0  
1      NaN     NaN     NaN  
2   2672.0  2733.0  2559.0  
3    346.0   699.0   226.0  
4   1672.0  1961.0  1521.0  
..     ...     ...     ...  
80   795.0   564.0   858.0  
81   458.0   969.0   831.0  
82     0.0   889.0   396.0  
83   840.0     0.0   766.0  
84   428.0   833.0     0.0  

[85 rows x 86 columns]

In [5]:
bus_matrix.head()

id  BT25  BT07  BT13  BT10  BD01  BD02  BD05  BD06  BD09  ...  BL22  BL23  \
0  A1  2234  1766  1370  2384  2077  1938  1932  2472  1853  ...  2529  2558   
1  A2  1750  1294  1042  1912  1632  1787  2402  1988  1382  ...  2580  2314   
2  A3  1254   779   948  1397  1116  1271  2086  1594   866  ...  2265  1798   
3  A4  1741  1267   650  1885  1604  1726  2050  2082  1354  ...  2647  2346   
4  A5  2270  1640  2254  2414  1681  1453  2260  2348  1561  ...  2979   610   

   BT26  BL19  BT04  BT19  BL03  BL07  BT05  BT15  
0  1594  1861  1854  1850  2308  1811  1372  2128  
1  1486  1685  1472  1664  1818  1758   954  1717  
2  1356  1170   957  1149  1302  1243   341  1201  
3  1119  1700  1539  1638  1790  1599   814  1689  
4  2077  1731  1724  1255  1826  1442  2052  1394  

[5 rows x 70 columns]

In [6]:
transpose_bus_matrix = bus_matrix.transpose()
transpose_bus_matrix

0     1     2     3     4     5     6     7     8     9   ...    41  \
id      A1    A2    A3    A4    A5    A6    A7    A8    A9   A10  ...   A42   
BT25  2234  1750  1254  1741  2270  2628  1489  1230  3111  2575  ...  4172   
BT07  1766  1294   779  1267  1640  1979  1069  1933  2902  1793  ...  3964   
BT13  1370  1042   948   650  2254  2593  1479  2268  2604  2407  ...  3666   
BT10  2384  1912  1397  1885  2414  2693  1632  1603  3466  2642  ...  4528   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
BT19  1850  1664  1149  1638  1255  1641   830  2194  2663  1696  ...  3725   
BL03  2308  1818  1302  1790  1826  2178  1306  2232  3140  1992  ...  4202   
BL07  1811  1758  1243  1599  1442  1828   773  2140  2606  1866  ...  3668   
BT05  1372   954   341   814  2052  2391  1343  1774  2648  2205  ...  3709   
BT15  2128  1717  1201  1689  1394  1780  1135  2229  2969  1559  ...  4030   

        42    43    44    45    46    47    48    49    50  
id     A43   A44   A45   A46   A47   A48   A49   A50   A51  
BT25  1392  1982  2876   983  1322  1394   949  1225   949  
BT07   554  1562  2800   634   901   905   519   804   311  
BT13  1168  1387  2402  1052   837   278   629  1032   907  
BT10  1403  2126  3363  1127  1465  1538  1092  1368  1092  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
BT19   547  1323  2565   347   771   951   651   679   632  
BL03   753  1800  3041   806  1229  1409  1017  1137   914  
BL07   650  1266  2507   383   732   912   598   488   579  
BT05   966  1837  2413   838  1176   957   794  1079   705  
BT15   368  1629  2870   625  1049  1229   916   957   813  

[70 rows x 51 columns]

In [7]:
#set first row as header
transpose_bus_matrix.columns = transpose_bus_matrix.iloc[0]
transpose_bus_matrix = transpose_bus_matrix[1:]
transpose_bus_matrix

id      A1    A2    A3    A4    A5    A6    A7    A8    A9   A10  ...   A42  \
BT25  2234  1750  1254  1741  2270  2628  1489  1230  3111  2575  ...  4172   
BT07  1766  1294   779  1267  1640  1979  1069  1933  2902  1793  ...  3964   
BT13  1370  1042   948   650  2254  2593  1479  2268  2604  2407  ...  3666   
BT10  2384  1912  1397  1885  2414  2693  1632  1603  3466  2642  ...  4528   
BD01  2077  1632  1116  1604  1681  2022  1161  2163  2995  1836  ...  4056   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
BT19  1850  1664  1149  1638  1255  1641   830  2194  2663  1696  ...  3725   
BL03  2308  1818  1302  1790  1826  2178  1306  2232  3140  1992  ...  4202   
BL07  1811  1758  1243  1599  1442  1828   773  2140  2606  1866  ...  3668   
BT05  1372   954   341   814  2052  2391  1343  1774  2648  2205  ...  3709   
BT15  2128  1717  1201  1689  1394  1780  1135  2229  2969  1559  ...  4030   

id     A43   A44   A45   A46   A47   A48   A49   A50   A51  
BT25  1392  1982  2876   983  1322  1394   949  1225   949  
BT07   554  1562  2800   634   901   905   519   804   311  
BT13  1168  1387  2402  1052   837   278   629  1032   907  
BT10  1403  2126  3363  1127  1465  1538  1092  1368  1092  
BD01   654  1655  2897   455   998  1146   791   906   529  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
BT19   547  1323  2565   347   771   951   651   679   632  
BL03   753  1800  3041   806  1229  1409  1017  1137   914  
BL07   650  1266  2507   383   732   912   598   488   579  
BT05   966  1837  2413   838  1176   957   794  1079   705  
BT15   368  1629  2870   625  1049  1229   916   957   813  

[69 rows x 51 columns]

In [8]:
# Convert transpose_bus_matrix to a numpy array without the indexes and column headers
array_without_indexes = transpose_bus_matrix.to_numpy()
print(array_without_indexes)

[[2234 1750 1254 ... 949 1225 949]
 [1766 1294 779 ... 519 804 311]
 [1370 1042 948 ... 629 1032 907]
 ...
 [1811 1758 1243 ... 598 488 579]
 [1372 954 341 ... 794 1079 705]
 [2128 1717 1201 ... 916 957 813]]


In [9]:
demand= accomodations_clusters['total_accommodates'].to_numpy()
demand

array([ 6969,  6395,  2801,  7026,  4909,  1545,  6342,  6399,  1171,
        4117,  3110,  3088,  5080,  4779,  2666,  9095,  7555,  4679,
        2111,  3376,  7538,  7068,  6853,  1576,  2974,  2110,  1319,
       10383,  1268,   273,  8063,  8239,  3833,  6408,  7028,  2057,
        4099,  2060,  2646,  2505,  6751,   934,  4119,  9229,   563,
        7296,  2670,  2156,  2263,  1619, 12812])

In [11]:
from __future__ import print_function
from ortools.sat.python import cp_model as cp
import matplotlib.pyplot as plt

def plot_assignment(customers, warehouses, x, solver):
    num_customers = len(customers)
    num_warehouses = len(warehouses)
    assigned = [[solver.Value(x[c, w]) for w in warehouses] for c in customers]

    plt.imshow(assigned, cmap='Blues', interpolation='nearest')
    plt.xticks(range(num_warehouses), ['W {}'.format(w) for w in warehouses])
    plt.yticks(range(num_customers), ['C {}'.format(c) for c in customers])
    plt.xlabel('Warehouses')
    plt.ylabel('Customers')
    plt.title('Customer-Warehouse Assignment')
    plt.colorbar(label='Assignment')
    plt.show()


: 

In [ ]:

def main():
    # Model
    model = cp.CpModel()
    
    # Data declaration
    p = 10
    num_customers = 51
    customers = list(range(num_customers))
    num_warehouses = 69
    warehouses = list(range(num_warehouses))
    distance = array_without_indexes


    # Variable declaration
    open = [model.NewIntVar(0, 1, 'open[%i]' % w) for w in warehouses]
    x = {}
    for c in customers:
        for w in warehouses:
            x[c, w] = model.NewIntVar(0, 1, 'x[%i,%i]' % (c, w))

    z = model.NewIntVar(0, 1000, 'z') 

    # Constraints
    model.Add(z == sum([demand[c] * distance[c][w] * x[c, w] for c in customers for w in warehouses]))

    for c in customers:
        model.Add(sum([x[c, w] for w in warehouses]) == 1)


    model.Add(sum(open) == p)
    for c in customers:
        for w in warehouses:
            model.Add(x[c, w] <= open[w])

    # Objective function
    model.Minimize(z)

    # Model solution
    solver = cp.CpSolver()
    status = solver.Solve(model)

    if status == cp.OPTIMAL:
        print('z:', solver.Value(z))
        print('open:', [solver.Value(open[w]) for w in warehouses])
        for c in customers:
            for w in warehouses:
                print(solver.Value(x[c, w]), end=' ')
            print()
        print()

        plot_assignment(customers, warehouses, x, solver)

    print('WallTime:', solver.WallTime())

if __name__ == '__main__':
    main()

In [18]:
import pulp

# Set the number of bus stops to locate
p = 15

# Assume bus_matrix rows: accommodations; columns: candidate bus stops
accom = list(bus_matrix.index)
bus_stops = list(bus_matrix.columns[1:])

# Create the optimization problem
model = pulp.LpProblem("p_median", pulp.LpMinimize)

# Decision variable: x[j] = 1 if bus stop j is selected
x = pulp.LpVariable.dicts("x", bus_stops, cat="Binary")
# Decision variable: y[i,j] = 1 if accommodation i is assigned to bus stop j
y = pulp.LpVariable.dicts("y", [(i, j) for i in accom for j in bus_stops], cat="Binary")

# Objective: minimize total distance from each accomodation to its assigned bus stop
model += pulp.lpSum(bus_matrix.loc[i, j] * y[(i, j)] for i in accom for j in bus_stops)

# Constraint: each accommodation must be assigned to exactly one bus stop
for i in accom:
    model += pulp.lpSum(y[(i, j)] for j in bus_stops) == 1

# Constraint: an accommodation can be assigned to a bus stop only if that bus stop is selected
for i in accom:
    for j in bus_stops:
        model += y[(i, j)] <= x[j]

# Constraint: exactly p bus stops are selected
model += pulp.lpSum(x[j] for j in bus_stops) == p

# Solve the model
model.solve()

selected = [j for j in bus_stops if x[j].varValue > 0.5]
print("Selected bus stops:", selected)

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /opt/anaconda3/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/pg/ms9txxdj6xj6l0sxpljp5j940000gn/T/511d0efe7235411b96f54fcbd9f085c2-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /var/folders/pg/ms9txxdj6xj6l0sxpljp5j940000gn/T/511d0efe7235411b96f54fcbd9f085c2-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 3576 COLUMNS
At line 24898 RHS
At line 28470 BOUNDS
At line 32059 ENDATA
Problem MODEL has 3571 rows, 3588 columns and 10626 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 48018 - 0.01 seconds
Cgl0004I processed model has 3571 rows, 3588 columns (3588 integer (3588 of which binary)) and 10626 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 48018

In [20]:
#map only selected bus stops ['BD14', 'BD15', 'BT03', 'BL14', 'BT23', 'BT18', 'BL23', 'BL07', 'BT05']
# Add markers for each cluster
map_center = [accomodations_clusters['avg_latitude'].mean(), accomodations_clusters['avg_longitude'].mean()]
m2 = folium.Map(location=map_center, zoom_start=10)

for _, row in accomodations_clusters.iterrows():
    folium.Marker(
        location=[row['avg_latitude'], row['avg_longitude']],
        popup=f"ID: {row['id']}<br>Total Accommodates: {row['total_accommodates']}<br>Count: {row['count']}",
    ).add_to(m2)
# Add markers for each venue
for _, row in venues.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=f"ID: {row['id']}<br>Approx. Capacity: {row['Approx. Capacity']}<br>Venue: {row['Venue']}",
        icon=folium.Icon(color='purple')
    ).add_to(m2)

for _, row in bus_terminals[bus_terminals['id'].isin(selected)].iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=f"ID: {row['id']}<br>Terminal: {row['FACILITY']}",
        icon=folium.Icon(color='lightgreen', icon='ok-sign')
    ).add_to(m2)
# Display the map with selected bus stops
m2